name: Publish Release
on:
  push:
    branches:
      - 20-github-action-workflow # TODO: Change this to main

jobs:
  build-and-publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./videmo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run react-build

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: false
          package_root: ./videmo # Specify the correct directory where package.json is located
          build_script_name: build
          skip_build: false
          use_vue_cli: false
          max_attempts: 1
