name: Publish Release
on:
  push:
    branches:
      - 20-github-action-workflow # TODO: Change this to main

jobs:
  build-and-publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./videmo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run react-build

      - name: Build/release Electron app
        working-directory: ./videmo  # Set the working directory to the "videmo" subdirectory
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}