name: Publish Release
on:
  push:
    branches:
      - 20-github-action-workflow # TODO: Change this to main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./videmo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install wine, xvfb, and other dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine xvfb

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run react-build

      - name: Start xvfb (virtual display)
        run: Xvfb :99 -screen 0 1024x768x24 >/dev/null 2>&1 &

      - name: Publish Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron-builder --win --x64 --publish always