
name: Build/release

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./videmo

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run react-build

      - name: Publish app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install electron-builder -g
          electron-builder --win --x64 --publish always